language: go

go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - tip

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-base-dev
install: make deps
script: make test
